global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: custom
    scrape_interval: 1m
    scrape_timeout: 30s
    file_sd_configs:
    - files:
      - '/etc/prometheus/service_discovery.json'
