version: '3.8'

networks:

  grafana:
    external: false

volumes:

  prometheus:
  grafana:

services:

  exporter:
    build:
      context: ./exporter
    container_name: exporter
    restart: unless-stopped
    networks:
      - grafana
    ports:
      - 9100:9100
    volumes:
      - type: bind
        source: ./exporter/
        target: /app/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - exporter
    networks:
      - grafana
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      # - GF_PLUGIN_DIR=/grafana-plugins
      # - GF_INSTALL_PLUGINS=dpurge-foo-panel
      # - NODE_ENV=development
      # - GF_LOG_LEVEL=debug
      # - GF_DATAPROXY_LOGGING=1
      # - GF_LOG_FILTERS=plugin.jdp-dpurgeflashcards-panel:debug
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=dpurge-lab1-panel,dpurge-lab1-app
    volumes:
      - type: bind
        source: ./grafana/
        target: /workspace/
      - type: bind
        source: ./grafana/plugins/dpurge-lab1-panel/dist
        target: /var/lib/grafana/plugins/dpurge-lab-panel
      - type: bind
        source: ./grafana/plugins/dpurge-lab1-app/dist
        target: /var/lib/grafana/plugins/dpurge-lab-app
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning/
      - type: volume
        source: grafana
        target: /var/lib/grafana