Vagrant.configure("2") do |config|

  servers=[
    {
      :hostname => "srv01",
      :box => "generic/ubuntu2010",
      :ip => "192.168.200.101",
      :ssh_port => '2201',
      :memory => 512,
      :cpus => 1
    }
  ]
  gateway="192.168.200.1"

  servers.each do |srv|
    config.vm.define srv[:hostname] do |node|
      node.vm.box = srv[:box]
      node.vm.hostname = srv[:hostname]

      node.vm.provider :hyperv
      node.vm.network :public_network, auto_config: false
      node.vm.network "forwarded_port", guest: 22, host: srv[:ssh_port], id: "ssh"
      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.provision "shell", path: "./scripts/configure-static-ip.sh", :args => "#{srv[:ip]} #{gateway}"
      node.vm.provision :reload

      node.vm.provider :hyperv do |h|
        h.vmname = srv[:hostname]
        h.enable_virtualization_extensions = true
        h.linked_clone = true
        h.maxmemory = 2048
        h.memory = srv[:memory]
        h.cpus = srv[:cpus]
      end
    end
  end
end
