global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:

  - job_name: prometheus
    scrape_timeout: 10s
    static_configs:
      - targets:
        - localhost:9090

  - job_name: exporter
    scrape_timeout: 30s
    static_configs:
      - targets:
        - exporter:9100